language: ruby
sudo: required
cache: bundler
os:
- linux
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6 gcc-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo update-alternatives --config gcc
  - g++ --version
  - gem update --system
  - gem install bundler
  - gem --version
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - cd spec/types/test_files && make && cd -
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
